In [2]:
import numpy

In [4]:
n=numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [5]:
type(n)

numpy.ndarray

In [6]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [7]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [13]:
m=numpy.asarray([[123, 44, 324, 66],[],[]])
print(m)

[list([123, 44, 324, 66]) list([]) list([])]


In [14]:
import cv2

In [20]:
img_grey=cv2.imread("original.png",1)
print(img_grey)

[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


In [23]:
cv2.imwrite("newsmallgrey.png", img_grey)

True

In [29]:
for i in img_grey:
    print(i)

[[187 187 187]
 [158 158 158]
 [104 104 104]
 [121 121 121]
 [143 143 143]]
[[198 198 198]
 [125 125 125]
 [255 255 255]
 [255 255 255]
 [147 147 147]]
[[209 209 209]
 [134 134 134]
 [255 255 255]
 [ 97  97  97]
 [182 182 182]]


In [30]:
for i in img_grey.flat:
        print(i)

187
187
187
158
158
158
104
104
104
121
121
121
143
143
143
198
198
198
125
125
125
255
255
255
255
255
255
147
147
147
209
209
209
134
134
134
255
255
255
97
97
97
182
182
182


In [33]:
ims=numpy.hstack(img_grey)
print(ims)

[[187 187 187 198 198 198 209 209 209]
 [158 158 158 125 125 125 134 134 134]
 [104 104 104 255 255 255 255 255 255]
 [121 121 121 255 255 255  97  97  97]
 [143 143 143 147 147 147 182 182 182]]


In [34]:
ims=numpy.vstack(img_grey)
print(ims)

[[187 187 187]
 [158 158 158]
 [104 104 104]
 [121 121 121]
 [143 143 143]
 [198 198 198]
 [125 125 125]
 [255 255 255]
 [255 255 255]
 [147 147 147]
 [209 209 209]
 [134 134 134]
 [255 255 255]
 [ 97  97  97]
 [182 182 182]]


In [38]:
lst=numpy.vsplit(ims,3)
print(lst)

[array([[187, 187, 187],
       [158, 158, 158],
       [104, 104, 104],
       [121, 121, 121],
       [143, 143, 143]], dtype=uint8), array([[198, 198, 198],
       [125, 125, 125],
       [255, 255, 255],
       [255, 255, 255],
       [147, 147, 147]], dtype=uint8), array([[209, 209, 209],
       [134, 134, 134],
       [255, 255, 255],
       [ 97,  97,  97],
       [182, 182, 182]], dtype=uint8)]
